In [1]:
import tensorflow as tf
import numpy as np

演算の途中でも、numpy のデータを扱うように、自由に値を見る事が出来ます。

In [2]:
tf.executing_eagerly()

True

In [3]:
x = tf.constant(8.0) # 8.0, shape=()
print(x)
with tf.GradientTape() as t:
    t.watch(x)
    y = x * x
    # 元の入力テンソル x に対する y の微分
    dy_dx = t.gradient(y, x) # 16.0, shape=()
print(dy_dx)

tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(16.0, shape=(), dtype=float32)


In [4]:
x = tf.constant(3.0) # 3.0, shape=()
print(x)
with tf.GradientTape() as t:
    t.watch(x)
    with tf.GradientTape() as tt:
        tt.watch(x)
        y = x * x
        dy_dx = tt.gradient(y, x) # 6.0, shape=()
        dy2_dx2 = t.gradient(dy_dx, x) # 2.0, shape=()
print(dy_dx)
print(dy2_dx2)

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


reduce_sum = 配列内のすべての要素を足し算する関数。<br>
multiply = テンソルの要素の掛け算です。

In [5]:
x = tf.ones((2, 2)) # x = [[1. 1.] [1. 1.]]
with tf.GradientTape() as t:
    # xを監視対象にしている。
    t.watch(x)
    y = tf.reduce_sum(x) # 4.0, shape=()
    z = tf.multiply(y, y) # 16.0, shape=()
dz_dx = t.gradient(z, x) # [[8. 8.] [8. 8.]], shape=(2, 2)

# 元の入力テンソル x に対する z の微分
print(y)
print(z)
print(dz_dx) # [[8. 8.] [8. 8.]], shape=(2, 2)

tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(16.0, shape=(), dtype=float32)
tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [6]:
x = tf.constant(8.0) # 8.0, shape=()
print(x)
with tf.GradientTape() as t:
    t.watch(x)
    y = x
    dy_dx = t.gradient(y, x) # 1.0, shape=()
print(y)
print(dy_dx)

tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(8.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)


In [7]:
i, x, N = 0, 0, 10
while i < N:
    i, x = i + 1, x + i
print((i, x))

(10, 45)


In [8]:
def condition(i, x):
    return i < 10

def update(i, x):
    print('update  =',i, x)
    return i + 1, i + x

init_val = (0, 0)
tf.while_loop(cond=condition, body=update, loop_vars=init_val)

update  = 0 0
update  = 1 0
update  = 2 1
update  = 3 3
update  = 4 6
update  = 5 10
update  = 6 15
update  = 7 21
update  = 8 28
update  = 9 36


(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>)

In [9]:
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
# b = lambda i: (tf.add(i, 1), )
def b(i):
    print(i)
    return (tf.add(i, 1), )
tf.while_loop(c, b, [i])

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


(<tf.Tensor: shape=(), dtype=int32, numpy=10>,)

unique_with_counts = テンソルの要素の数を取得する<br>
uniqueTimes = [0.1 1.5 1.9] ユニークな要素の数<br>
uniqueIndices = [0 0 1 2 2 2] ユニークなインデックスをふる。 <br>
counts = [2 1 3] ユニークな要素数<br>
gather_nd = params からスライスを収集し、 indices で指定された形状のTensorに入れます。<br>

In [10]:
import tensorflow as tf

times = tf.constant([0.1, 0.1, 1.5, 1.9, 1.9, 1.9])
posit = tf.constant([2.1, 3.5, 0.4, 1.3, 2.7, 3.5])

vel = tf.constant([0.5,0.7,1.0])

uniqueTimes, uniqueIndices, counts = tf.unique_with_counts(times)

tf.gather_nd(vel,uniqueIndices[:,None])*posit

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1.05, 1.75, 0.28, 1.3 , 2.7 , 3.5 ], dtype=float32)>

gather_nd = テンソルと、そのテンソル内の位置を表すインデックスを提供します。指定したインデックスに対応するテンソルの要素を返します。

In [11]:
# テンソルと、そのテンソル内の位置を表すインデックスを提供します。指定したインデックスに対応するテンソルの要素を返します。
x = [[1,2,3],[4,5,6]]
y = tf.gather_nd(x, [[1,1],[1,2]]) # <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>
y = y.numpy()
y[0], y[1]

(5, 6)

In [12]:
x = tf.constant([0.1, 0.1, 1.5, 4.5, 3.6, 1.2])
y = tf.constant([3.1, 2.3, 1.4, 2.3, 4.4, 3.1])

uniqueIndices = tf.constant([0, 1, 2, 3, 4, 5])

x = tf.gather_nd(x, uniqueIndices[:,None])
y = tf.gather_nd(y, uniqueIndices[:,None])

tf.multiply(x, y) # shape=(6,), array([ 0.31    ,  0.23    ,  2.1     , 10.349999, 15.84    ,  3.72    ])

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([ 0.31    ,  0.23    ,  2.1     , 10.349999, 15.84    ,  3.72    ],
      dtype=float32)>

再帰関数(Recursive function)

In [13]:
def recurrence(n):
    if n ==1:
        return 1
    else:
        return recurrence(n-1)+4
    
for i in range(1,6):
    print(i,recurrence(i),4*i-3)

1 1 1
2 5 5
3 9 9
4 13 13
5 17 17


In [33]:
x = np.array([0.1, 1.2, 0.5, 4.5, 3.6, 1.2, 3.1, 2.3, 0.4, 0.3, 4.4, 3.1])

def select_min(a, b):
    if a > b:
        return b
    return a

arg = 1.0
for i in range(400):
    num = np.array([])
    for x_f in x:
        p = select_min(arg, x_f)
        num = np.append(num, np.array(p))
    arg = np.mean(num)
    if i % 10 == 0:
        print(num, arg)

[0.1 1.  0.5 1.  1.  1.  1.  1.  0.4 0.3 1.  1. ] 0.775
[0.1        0.28414312 0.28414312 0.28414312 0.28414312 0.28414312
 0.28414312 0.28414312 0.28414312 0.28414312 0.28414312 0.28414312] 0.2687978569208676
[0.1        0.17713827 0.17713827 0.17713827 0.17713827 0.17713827
 0.17713827 0.17713827 0.17713827 0.17713827 0.17713827 0.17713827] 0.1707100785307387
[0.1        0.13231352 0.13231352 0.13231352 0.13231352 0.13231352
 0.13231352 0.13231352 0.13231352 0.13231352 0.13231352 0.13231352] 0.12962072680915127
[0.1        0.11353626 0.11353626 0.11353626 0.11353626 0.11353626
 0.11353626 0.11353626 0.11353626 0.11353626 0.11353626 0.11353626] 0.11240823762232084
[0.1        0.10567039 0.10567039 0.10567039 0.10567039 0.10567039
 0.10567039 0.10567039 0.10567039 0.10567039 0.10567039 0.10567039] 0.10519785898178607
[0.1        0.10237535 0.10237535 0.10237535 0.10237535 0.10237535
 0.10237535 0.10237535 0.10237535 0.10237535 0.10237535 0.10237535] 0.10217740333614607
[0.1        0.10

In [38]:
a = tf.constant([1, 10, 26.9, 2.8, 166.32, 62.3])
b = tf.constant([3.1, 2.3, 1.4, 2.3, 4.4, 3.1])
a_arr = tf.sort(a).numpy()
b_arr = tf.sort(b).numpy()

a_arr[0], b_arr[0]

(1.0, 1.4)

In [48]:
x = tf.constant(2)
y = tf.constant(5)
def f1(): return tf.multiply(x, 17)
def f2(): return tf.add(y, 23)
r = tf.cond(tf.less(x, y), f1, f2)
# rはf1（）に設定されます。
# f2の操作（例：tf.add）は実行されません。
x,r

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=34>)

In [70]:
@tf.function
def mini_func(x):
    return x * x

x = tf.constant(5.0)
with tf.GradientTape() as t:
    t.watch(x)
    result = mini_func(x)
    dy_dx = t.gradient(result, x)
print(dy_dx) # tf.Tensor(10.0, shape=(), dtype=float32)

tf.Tensor(10.0, shape=(), dtype=float32)


In [71]:
@tf.function
def mini_func(x):
  return x * x

x = tf.Variable(5.0)
with tf.GradientTape() as t:
  result = mini_func(x)
dy_dx = t.gradient(result, x)
print(dy_dx) # tf.Tensor(10.0, shape=(), dtype=float32)

tf.Tensor(10.0, shape=(), dtype=float32)


In [74]:
def f(x, y):
  output = 1.0
  for i in range(y):
    if i > 1 and i < 5:
      output = tf.multiply(output, x)
  return output

def grad(x, y):
  with tf.GradientTape() as t:
    t.watch(x)
    out = f(x, y)
  return t.gradient(out, x) 

x = tf.convert_to_tensor(2.0)
grad(x, 6).numpy() # 12.0

12.0